// This file was auto-generated by ML.NET Model Builder. 

using System;
using GoingGreenBlazorML.Model;

namespace GoingGreenBlazorML.ConsoleApp
{
    class Program
    {
        static void Main(string[] args)
        {
            // Create single instance of sample data from first line of dataset for model input
            ModelInput sampleData = new ModelInput()
            {
                Brand = @"Xiaomi",
                Series = @"series 6",
                Consumption = 99F,
                EnergyClass = @"A",
                Colour = @"brown",
                Weight = 19F,
                Diagonal = 214F,
                IsSmart = @"true",
                Resolution = @"8K",
                Depth = @"NULL",
                Doors = @"NULL",
                HasFreezer = @"NULL",
                Height = @"NULL",
                Volume = @"NULL",
                Width = @"NULL",
                Type = @"Television",
            };

            // Make a single prediction on the sample data and print results
            var predictionResult = ConsumeModel.Predict(sampleData);

            Console.WriteLine("Using model to make single prediction -- Comparing actual Price with predicted Price from sample data...\n\n");
            Console.WriteLine($"Brand: {sampleData.Brand}");
            Console.WriteLine($"Series: {sampleData.Series}");
            Console.WriteLine($"Consumption: {sampleData.Consumption}");
            Console.WriteLine($"EnergyClass: {sampleData.EnergyClass}");
            Console.WriteLine($"Colour: {sampleData.Colour}");
            Console.WriteLine($"Weight: {sampleData.Weight}");
            Console.WriteLine($"Diagonal: {sampleData.Diagonal}");
            Console.WriteLine($"IsSmart: {sampleData.IsSmart}");
            Console.WriteLine($"Resolution: {sampleData.Resolution}");
            Console.WriteLine($"Depth: {sampleData.Depth}");
            Console.WriteLine($"Doors: {sampleData.Doors}");
            Console.WriteLine($"HasFreezer: {sampleData.HasFreezer}");
            Console.WriteLine($"Height: {sampleData.Height}");
            Console.WriteLine($"Volume: {sampleData.Volume}");
            Console.WriteLine($"Width: {sampleData.Width}");
            Console.WriteLine($"Type: {sampleData.Type}");
            Console.WriteLine($"\n\nPredicted Price: {predictionResult.Score}\n\n");
            Console.WriteLine("=============== End of process, hit any key to finish ===============");
            Console.ReadKey();
        }
    }
}
