// This file was auto-generated by ML.NET Model Builder. 

using Microsoft.ML.Data;

namespace PricePredictionML.Model
{
    public class ModelInput
    {
        [ColumnName("Brand"), LoadColumn(0)]
        public string Brand { get; set; }


        [ColumnName("Series"), LoadColumn(1)]
        public string Series { get; set; }


        [ColumnName("Consumption"), LoadColumn(2)]
        public float Consumption { get; set; }


        [ColumnName("EnergyClass"), LoadColumn(3)]
        public string EnergyClass { get; set; }


        [ColumnName("Colour"), LoadColumn(4)]
        public string Colour { get; set; }


        [ColumnName("Weight"), LoadColumn(5)]
        public float Weight { get; set; }


        [ColumnName("Diagonal"), LoadColumn(6)]
        public float Diagonal { get; set; }


        [ColumnName("IsSmart"), LoadColumn(7)]
        public string IsSmart { get; set; }


        [ColumnName("Resolution"), LoadColumn(8)]
        public string Resolution { get; set; }


        [ColumnName("Depth"), LoadColumn(9)]
        public string Depth { get; set; }


        [ColumnName("Doors"), LoadColumn(10)]
        public string Doors { get; set; }


        [ColumnName("HasFreezer"), LoadColumn(11)]
        public string HasFreezer { get; set; }


        [ColumnName("Height"), LoadColumn(12)]
        public string Height { get; set; }


        [ColumnName("Volume"), LoadColumn(13)]
        public string Volume { get; set; }


        [ColumnName("Width"), LoadColumn(14)]
        public string Width { get; set; }


        [ColumnName("Type"), LoadColumn(15)]
        public string Type { get; set; }


        [ColumnName("Price"), LoadColumn(16)]
        public float Price { get; set; }


    }
}
